### ISSUE TITLE
Usage of the program

### ISSUE THREAD

**Issue by fieterovich** [silmae/HyperBlend#1]
Hi! 

Thanks for this implementation, I have been looking to run it since a couple of days but I can't get it to be done. Is there any tutorial or instructions for somebody who is new to this type of software (and blender)? I tried running bs_render_single.py from IDE, from Conda Prompt, and from blender itself, but nothing seems to work.

Also, I tried to run __main__.py from windows cmd, from my IDE, and from Conda prompt, but it throws errors in references. I tried changing all the references to match what is being called, but I end up with an error that some files (and the directory optimization) does not exist. Tried to run code from the readme, but still can't get to work.

Would be very helpful if somebody can help me through some basic follow up on how to run this implementation.

Best regards!

**Comment by 11kaks** [comment]
Hello fieterovich! Nice that you have found us.

By references, do you mean the imports? Make sure your working directory is `HyperBlend\src`. In Pycharm, you can check it from Run -> Edit configurations. Are you using Pycharm as an IDE? You can get it from https://www.jetbrains.com/pycharm/ for free and it will be more easy for me to help you if we are using the same IDE. 

You should probably stick with running the code from the IDE for now. 

The Optimization directory is created automatically when an `optimization` object is created. Easiest way to get started is to make the main look like this:

```python
if __name__ == '__main__':
    # log to stdout instead of stderr for nice coloring
    logging.basicConfig(stream=sys.stdout, level='INFO')
    from src import presets
    presets.optimize_default_target(spectral_resolution=50)
```

If that works, everything else should too. If you get an error regarding the Blender location (can't remember how the error looks like exactly), check `blender_executable_path_win` from` constants.py` and set it to point to your Blender executable.

Try these and tell me where it gets you. If you get errors, please copypaste or post a picture of the error.

**Comment by fieterovich** [comment]
Hi! Thanks for the answer.

I have downloaded PyCharm (I was using Sublime Text 3) and loaded the conda environment created using the command provided in the readme.

Then, with that conda environment as interpreter, tried to run the `__main__.py`. As far as I know, the working directory is `Hyperblend\src` (I will send a picture of this) and I keep getting import errors 😢 

`C:\Users\Adminitrador\anaconda3\envs\hb2\python.exe C:/Users/Adminitrador/Desktop/2022/Magister/Hyperblend/Hyperblend_2/HyperBlend/src
Traceback (most recent call last):
  File "C:\Users\Adminitrador\anaconda3\envs\hb2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Adminitrador\anaconda3\envs\hb2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:/Users/Adminitrador/Desktop/2022/Magister/Hyperblend/Hyperblend_2/HyperBlend/src\__main__.py", line 12, in <module>
    from src import presets
ModuleNotFoundError: No module named 'src'`

` Process finished with exit code 1 `

And here's the configuration tab you mentioned:

![image](https://user-images.githubusercontent.com/62263860/163875456-36832e69-f7aa-4dca-9409-d8ba8dc282ae.png)

If there is anything I'm missing regarding the configuration, please tell me. Thank you very much again for your time!

Side note: there is a directory `Hyperblend_2` because I have a `Hyperblend` original directory where I changed all the references in the imports and I get errors too, now I'm getting an error importing `toml` in `toml_handling`, says it doesn't exist, but I had an error back then with the `optimization` folder

**Comment by 11kaks** [comment]
Thanks for the screen capture. I see the problem now. 

To `Script path` put `...\HyperBlend2\HyperBlend\__main__.py` (these are double underscores). This is the file that is run by Python.

To `Working directory`put `...\HyperBlend2\HyperBlend\src`. The working directory must be right so that all other stuff is found, such as imports and other directories used by the software. 

Otherwise it seems goog so this should get you going. Let me know if you run into more problems.

**Comment by fieterovich** [comment]
It's not working either, as the `Hyperblend` folder does not have the `__main__.py` file, it raises:

`C:\Users\Adminitrador\anaconda3\envs\hb2\python.exe C:/Users/Adminitrador/Desktop/2022/Magister/Hyperblend/Hyperblend_2/HyperBlend/__main__.py
C:\Users\Adminitrador\anaconda3\envs\hb2\python.exe: can't open file 'C:/Users/Adminitrador/Desktop/2022/Magister/Hyperblend/Hyperblend_2/HyperBlend/__main__.py': [Errno 2] No such file or directory`

Is the goal trying to get the `__main__.py` file run as if it was in the `Hyperblend` folder and not in the `src` folder? I have never done that before in python, but I think this is the problem, and I'm not sure of how to solve it yet, I'll keep trying.

Thanks, and sorry for the inconveniences.

**Comment by 11kaks** [comment]
Ah, yes.. my bad. I forgot the src from Script path. So it should be `...\HyperBlend2\HyperBlend\src\__main__.py`

**Comment by fieterovich** [comment]
Still getting the module import error when I put the script path `...\HyperBlend2\HyperBlend\src\__main__.py`

`Traceback (most recent call last):
  File "C:/Users/Adminitrador/Desktop/2022/Magister/Hyperblend/Hyperblend_2/HyperBlend/src/__main__.py", line 12, in <module>
    from src import presets
ModuleNotFoundError: No module named 'src'`

The only way I figured to solve that was changing all the imports from all the scripts, but I think it should not be the way. 

For example, the error raised by  `from src import presets` is solved when changed to `import presets` because `presets.py` is in the same `src` folder. `from src import presets` would work if `__main__.py` was in the parent directory of `src` (`Hyperblend`). But if I do that change, moving `__main__.py` to the parent directory, other errors are raised.

**Comment by 11kaks** [comment]
I agree that changing imports and moving files around should not be a solution. I have tested this project on about five different computers and always got it to work without hussle. I'm running out of ideas. 

Here is an article on Python importing, which can be quite cumbersome https://fortierq.github.io/python-import/

Based on the article, I would think that you having checked the "Add stuff to PYTHONPATH" in your configuration should have taken care of the imports. Maybe you can try to clone it once more and build a fresh Pycharm project, but I dont know if it'll help. No need to make another Conda environment though I think.

My configuration looks the same as yours

![image](https://user-images.githubusercontent.com/33941896/164291791-0d120acf-845d-4e8a-9f67-c85c3babf403.png)

Sorry that I can't be of more help now. Let me know if you can solve it in case someone else runs into this issue. I may need to rethink how the imports are arranged and see if I can make them more reliable, but I don't have the time now.

**Comment by fieterovich** [comment]
Don't worry! I'll try to figure it out, if I get it solved I will post again. Will be working on this this days. 
Is there any possibility to make a short video of the general use of this software? Something like a basic walk-through, So when I get the imports problem solved, it would be more easy to get into the software. 

Thank you very much again :)

**Comment by fieterovich** [comment]
Ok so tried running the code by changing every import available in the main source code and did the `__main__.py` run that was in the README.md (or the one that was commented here before) and I can have the program running (creates `optimization` folder and starts to 'Optimize wavelenghts' as shown in this picture:

![image](https://user-images.githubusercontent.com/62263860/165655655-5ccaf3ee-8b68-4b62-afab-9269034222dd.png)

But then i get an error which is calling to `multiprocessing` library, but I couldn't solve what is going wrong (after a couple hours researching through stackoverflow and other webpages)

![image](https://user-images.githubusercontent.com/62263860/165655731-7a7b6ece-9e9a-4be5-b314-31297c199b54.png)

Any ideas of what is going on with the error? 

Thank you!

P.S. Also tried running a new PC, in windows too, and tried reinstalling conda, reinstalling pycharm, but nothing solved the `import` errors :( so this is the only thing that made me get one step up in running this code.

**Comment by 11kaks** [comment]
You can try to run it without using threads by changing `use_threads` to `False` in `o.run_optimization()` call in presets.py (line 24). Then it will not use multiprocessing at all, so it will be very slow. Let me know if it works that way at all. Multiprocessing makes debugging very difficult as it somehow hides errors from other parts of the code. So without it, the errors that do happen can be fixed more easily.

Sorry to hear that the imports caused so much trouble!

As for a tutorial video, I might do one once i get new features done, but right now I dont have time for that.

**Comment by fieterovich** [comment]
Ok so I got it working, the problem was actually the blender path. Now I can have the optimizations running and looking forward to test this program :) Thank you very much

**Comment by 11kaks** [comment]
Good to hear =) I will close this issue now
